services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  llm_proxy:
    build: ./llm_proxy_image
    container_name: llm_proxy
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - LOCAL_MODEL_URL=http://local-llm:5000/generate
    depends_on:
      - redis

  local-llm:
    build: ./local_llm_image
    container_name: local_llm
    ports:
      - "5000:5000"