model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: ollama/llama3
    litellm_params:
      model: ollama/llama3
      api_base: os.environ/OLLAMA_API_BASE
  - model_name: ollama/llama2
    litellm_params:
      model: ollama/llama2
      api_base: os.environ/OLLAMA_API_BASE

general_settings:
  master_key: sk-1234